import { createContext } from "react";

// ── Character Avatar Paths ──
export const AVATAR_ZORK = "/assets/avatar-zork.webp";
export const AVATAR_PINO = "/assets/avatar-pino.webp";

// ── Base UI Style ──
export const BASE_UI = {
  radius: "0px",
  radiusLg: "0px",
  radiusFull: "0px",
  borderStyle: "solid",
  borderWidth: "2px",
  cornerBrackets: true,
  boxShadow: "none",
  glowShadow: true,
  barBg: "rgba(10,10,18,0.95)",
  transitionStyle: "lines",
  fontWeightDisplay: "normal",
  fontWeightHeading: "normal",
  letterSpacingTitle: "0.08em",
  subtitleFont: "inherit",
  italicSubtitle: true,
  dividerWidth: "60px",
  dividerHeight: "2px",
  dividerRadius: "0px",
  stampFrame: true,
};

// ── Base Labels ──
export const BASE_LABELS = {
  todayCase: "TODAY'S REPORT",
  recentCases: "RECENT REPORTS",
  startButton: "調査を開始する",
  streak: "▸ 連続7日目",
  caseClosedTitle: "調査完了",
  caseClosedLabel: "REPORT FILED",
  investigationLabel: "OBSERVATION PHASE",
  confirmLabel: "CONFIRM PHASE",
  exploreLabel: "EXPLORE PHASE",
  keywordBank: "── KEYWORD BANK ──",
  exploreButton: "探究する",
  categoryIcons: ["📡", "📖", "🔥"],
  avatarLabels: ["Zo", "Pi"],
  charNames: ["ゾルク博士", "ピノ"],
  correctBanner: "確認成功 (CONFIRMED)",
  wrongBanner: "確認失敗 (ERROR)",
  watermark: "REPORT",
};

// ── Tap feedback utility ──
export const tapProps = {
  onTouchStart: e => { e.currentTarget.style.transform = "scale(0.96)"; },
  onTouchEnd: e => { e.currentTarget.style.transform = "scale(1)"; },
  onTouchCancel: e => { e.currentTarget.style.transform = "scale(1)"; },
};

// ── Theme Definitions ──
export const THEMES = {
  cyber: {
    id: "cyber", name: "サイバー調", nameEn: "CYBER STATION", icon: "⟁",
    appTitle: "地球人調査センター", appTitleEn: "EARTH OBSERVATION CENTER",
    subtitle: "─── 15分で地球を調査せよ ───",
    fonts: `@import url('https://fonts.googleapis.com/css2?family=DotGothic16&family=Noto+Sans+JP:wght@300;400;500&display=swap');`,
    fontDisplay: "'DotGothic16', monospace",
    fontBody: "'Noto Sans JP', sans-serif",
    vars: {
      bg: "#0a0a12", surface: "#12121e", border: "#2a2a3a",
      primary: "#e8e8f0", text: "#c8c8d8", textDim: "#6a6a80",
      accent: "#00ffaa", accentGlow: "rgba(0,255,170,0.3)",
      secondary: "#ff64c8", error: "#ff3c5a",
    },
    scanlines: true, scanlineColor: "rgba(0,0,0,0.06)",
    particles: true, particleColor: "var(--accent)",
    glitch: true,
    bgStyle: {},
    uiStyle: { ...BASE_UI },
    labels: { ...BASE_LABELS },
  },

  wamono: {
    id: "wamono", name: "和モダン怪奇", nameEn: "調査帖", icon: "朱",
    appTitle: "地球調査帖", appTitleEn: "CHIKYU-CHOSA-CHOU",
    subtitle: "─── 十五分にて地球を紐解け ───",
    fonts: `@import url('https://fonts.googleapis.com/css2?family=Shippori+Mincho:wght@400;600;800&family=Zen+Kaku+Gothic+New:wght@300;400;500&display=swap');`,
    fontDisplay: "'Shippori Mincho', serif",
    fontBody: "'Zen Kaku Gothic New', sans-serif",
    vars: {
      bg: "#f5f0e8", surface: "#ebe5d8", border: "#c8b89a",
      primary: "#1a1008", text: "#2a2018", textDim: "#8a7a60",
      accent: "#b8292f", accentGlow: "rgba(184,41,47,0.08)",
      secondary: "#2a5a3a", error: "#b8292f",
    },
    scanlines: false, scanlineColor: "transparent",
    particles: false, particleColor: "var(--accent)",
    glitch: false,
    bgStyle: { backgroundImage: "url(\"data:image/svg+xml,%3Csvg width='100' height='100' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.03'/%3E%3C/svg%3E\")" },
    uiStyle: {
      ...BASE_UI,
      radius: "4px", radiusLg: "8px", radiusFull: "8px",
      borderStyle: "double", borderWidth: "3px",
      cornerBrackets: false,
      glowShadow: false,
      barBg: "var(--surface)",
      transitionStyle: "centered",
      fontWeightDisplay: 800, fontWeightHeading: 600,
      italicSubtitle: false,
      dividerWidth: "40px", dividerHeight: "4px", dividerRadius: "2px",
    },
    labels: {
      ...BASE_LABELS,
      todayCase: "本日の調査",
      recentCases: "過去の調査",
      startButton: "調査を始める",
      streak: "七日連続",
      caseClosedTitle: "調査了",
      caseClosedLabel: "報告完了",
      investigationLabel: "観察",
      confirmLabel: "確認",
      exploreLabel: "探究",
      keywordBank: "─ 語句一覧 ─",
      exploreButton: "探究する",
      categoryIcons: ["巻", "書", "風"],
      avatarLabels: ["師", "弟"],
      charNames: ["師匠", "弟子"],
      correctBanner: "── 的中 ──",
      wrongBanner: "── 外れ ──",
      watermark: "了",
    },
  },

  noir: {
    id: "noir", name: "ノワール探偵", nameEn: "EARTH FILE", icon: "🔍",
    appTitle: "EARTH FILE", appTitleEn: "FIELD REPORT",
    subtitle: "─── The truth is in the details ───",
    fonts: `@import url('https://fonts.googleapis.com/css2?family=Special+Elite&family=Noto+Sans+JP:wght@300;400;500&display=swap');`,
    fontDisplay: "'Special Elite', 'Noto Sans JP', serif",
    fontBody: "'Noto Sans JP', sans-serif",
    vars: {
      bg: "#1c1a17", surface: "#252219", border: "#3d3830",
      primary: "#e8dcc8", text: "#c8b898", textDim: "#7a7060",
      accent: "#d4a843", accentGlow: "rgba(212,168,67,0.15)",
      secondary: "#c45c3e", error: "#c45c3e",
    },
    scanlines: false, scanlineColor: "transparent",
    particles: false, particleColor: "var(--accent)",
    glitch: false,
    bgStyle: {},
    uiStyle: {
      ...BASE_UI,
      cornerBrackets: false,
      boxShadow: "inset 0 0 30px rgba(0,0,0,0.3)",
      barBg: "rgba(28,26,23,0.95)",
    },
    labels: {
      ...BASE_LABELS,
      todayCase: "TODAY'S FIELD REPORT",
      startButton: "Open File",
      correctBanner: "CONFIRMED.",
      wrongBanner: "WRONG LEAD.",
      watermark: "FILED",
      avatarLabels: ["Dr", "Pi"],
      charNames: ["Dr.Zork", "Pino"],
    },
  },

  retro: {
    id: "retro", name: "90年代ネット", nameEn: "GeoCities", icon: "🌐",
    appTitle: "地球人調査センター★", appTitleEn: "EARTH HOMEPAGE",
    subtitle: "☆★☆ ようこそ！あなたは 4,821 人目の訪問者です ☆★☆",
    fonts: `@import url('https://fonts.googleapis.com/css2?family=DotGothic16&family=VT323&display=swap');`,
    fontDisplay: "'VT323', 'DotGothic16', monospace",
    fontBody: "'DotGothic16', monospace",
    vars: {
      bg: "#000060", surface: "#000040", border: "#0080ff",
      primary: "#ffffff", text: "#ffff00", textDim: "#00cccc",
      accent: "#00ff00", accentGlow: "rgba(0,255,0,0.15)",
      secondary: "#ff00ff", error: "#ff0000",
    },
    scanlines: true, scanlineColor: "rgba(0,0,80,0.12)",
    particles: false, particleColor: "var(--accent)",
    glitch: false,
    bgStyle: {},
    uiStyle: { ...BASE_UI, barBg: "rgba(0,0,60,0.95)", subtitleFont: "var(--font-display)" },
    labels: {
      ...BASE_LABELS,
      todayCase: "★ TODAY ★",
      recentCases: "☆ PAST ☆",
      startButton: ">> START <<",
      streak: "★ 7日連続 ★",
      investigationLabel: ">> OBSERVATION <<",
      confirmLabel: ">> CONFIRM <<",
      exploreLabel: ">> EXPLORE <<",
      avatarLabels: ["博", "ピ"],
      charNames: ["ハカセ", "ピノ"],
      correctBanner: "(^o^) 正解！",
      wrongBanner: "(>_<) 不正解",
      watermark: "CLEAR!",
    },
  },

  labnote: {
    id: "labnote", name: "理科室ノート", nameEn: "EARTH LAB NOTE", icon: "📓",
    appTitle: "地球観察ラボノート", appTitleEn: "EARTH LAB NOTE",
    subtitle: "─── 毎日15分の観察記録 ───",
    fonts: `@import url('https://fonts.googleapis.com/css2?family=Klee+One:wght@400;600&family=Zen+Kaku+Gothic+New:wght@300;400;500&display=swap');`,
    fontDisplay: "'Klee One', cursive",
    fontBody: "'Zen Kaku Gothic New', sans-serif",
    vars: {
      bg: "#f8f6f0", surface: "#ffffff", border: "#c8d8c8",
      primary: "#2a3a2a", text: "#3a4a3a", textDim: "#8a9a8a",
      accent: "#2a8a5a", accentGlow: "rgba(42,138,90,0.1)",
      secondary: "#d46a20", error: "#c84040",
    },
    scanlines: false, scanlineColor: "transparent",
    particles: false, particleColor: "var(--accent)",
    glitch: false,
    bgStyle: {
      backgroundImage: "linear-gradient(rgba(100,160,140,0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(100,160,140,0.08) 1px, transparent 1px)",
      backgroundSize: "20px 20px",
    },
    uiStyle: {
      ...BASE_UI,
      radius: "6px", radiusLg: "12px", radiusFull: "50%",
      cornerBrackets: false,
      boxShadow: "2px 2px 8px rgba(0,0,0,0.06)",
      glowShadow: false,
      barBg: "var(--surface)",
      stampFrame: false,
    },
    labels: {
      ...BASE_LABELS,
      todayCase: "今日の観察テーマ",
      startButton: "観察を始める",
      confirmLabel: "理解度チェック",
      exploreLabel: "深掘りテスト",
      avatarLabels: ["Dr", "Pi"],
      charNames: ["ゾルク先生", "ピノちゃん"],
      correctBanner: "正解です！",
      wrongBanner: "不正解…",
      watermark: "完了",
    },
  },

  vapor: {
    id: "vapor", name: "ヴェイパーウェイヴ", nameEn: "ＥＡＲＴＨ ＷＡＶＥ", icon: "🌴",
    appTitle: "ＥＡＲＴＨ　ＷＡＶＥ", appTitleEn: "地 球 波",
    subtitle: "─── ｅｖｅｒｙ　ｄａｙ　１５ｍｉｎ ───",
    fonts: `@import url('https://fonts.googleapis.com/css2?family=DotGothic16&family=Zen+Kaku+Gothic+New:wght@300;400;500&display=swap');`,
    fontDisplay: "'DotGothic16', monospace",
    fontBody: "'Zen Kaku Gothic New', sans-serif",
    vars: {
      bg: "#1a0a2e", surface: "#200e38", border: "#4a2a6a",
      primary: "#ffeeff", text: "#e0c0e8", textDim: "#9070a8",
      accent: "#00e5ff", accentGlow: "rgba(0,229,255,0.15)",
      secondary: "#ff71ce", error: "#ff3860",
    },
    scanlines: true, scanlineColor: "rgba(60,0,80,0.08)",
    particles: true, particleColor: "var(--secondary)",
    glitch: false,
    bgStyle: { backgroundImage: "linear-gradient(180deg, #1a0a2e 0%, #0a1628 50%, #1a0a2e 100%)" },
    uiStyle: { ...BASE_UI, letterSpacingTitle: "0.2em", barBg: "rgba(26,10,46,0.95)" },
    labels: {
      ...BASE_LABELS,
      todayCase: "ＴＯＤＡＹ",
      startButton: "ＳＴＡＲＴ",
      avatarLabels: ["Ｚ", "Ｐ"],
      charNames: ["Ｚｏｒｋ", "Ｐｉｎｏ"],
      correctBanner: "ＣＯＮＦＩＲＭＥＤ",
      wrongBanner: "ＥＲＲＯＲ",
      watermark: "ＤＯＮＥ",
    },
  },

  comic: {
    id: "comic", name: "コミック調", nameEn: "COMIC POP", icon: "💥",
    appTitle: "地球人クイズバトル！", appTitleEn: "EARTH QUIZ BATTLE!",
    subtitle: "── 毎日15分のスキルアップタイム！ ──",
    fonts: `@import url('https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@400;700;900&family=Zen+Kaku+Gothic+New:wght@300;400;500&display=swap');`,
    fontDisplay: "'M PLUS Rounded 1c', sans-serif",
    fontBody: "'Zen Kaku Gothic New', sans-serif",
    vars: {
      bg: "#fafafa", surface: "#ffffff", border: "#222222",
      primary: "#111111", text: "#222222", textDim: "#777777",
      accent: "#ff3366", accentGlow: "rgba(255,51,102,0.1)",
      secondary: "#3366ff", error: "#ff3366",
    },
    scanlines: false, scanlineColor: "transparent",
    particles: false, particleColor: "var(--accent)",
    glitch: false,
    bgStyle: {
      backgroundImage: "radial-gradient(circle, #00000008 1px, transparent 1px)",
      backgroundSize: "16px 16px",
    },
    uiStyle: {
      ...BASE_UI,
      radius: "10px", radiusLg: "16px", radiusFull: "50%",
      borderWidth: "3px",
      cornerBrackets: false,
      boxShadow: "4px 4px 0px var(--border)",
      glowShadow: false,
      barBg: "var(--surface)",
      transitionStyle: "centered",
      fontWeightDisplay: 900, fontWeightHeading: 700,
      italicSubtitle: false,
      letterSpacingTitle: "0.04em",
      dividerWidth: "50px", dividerHeight: "4px", dividerRadius: "2px",
    },
    labels: {
      ...BASE_LABELS,
      todayCase: "今日のバトル！",
      recentCases: "バトル履歴",
      startButton: "バトル開始！",
      streak: "🔥 7日連続！",
      caseClosedTitle: "バトル完了！",
      caseClosedLabel: "BATTLE CLEAR",
      investigationLabel: "ストーリー",
      confirmLabel: "クイズバトル",
      exploreLabel: "穴埋めチャレンジ",
      keywordBank: "── ワードリスト ──",
      exploreButton: "回答する！",
      categoryIcons: ["⚡", "📚", "🔥"],
      avatarLabels: ["博", "ピ"],
      charNames: ["ゾルク先生", "ピノ"],
      correctBanner: "大正解！💥",
      wrongBanner: "ハズレ…💦",
      watermark: "CLEAR",
    },
  },
};

export const ThemeContext = createContext(THEMES.cyber);
